---
abstract: 'Apache Solr JavaBin (de)serializer'
author:
  - 'James Raspass <jraspass@gmail.com>'
build_requires:
  B: 0
  Test::More: 0.96
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: JavaBin
provides:
  JavaBin:
    file: lib/JavaBin.pm
    version: 0.5
requires:
  DynaLoader: 0
  perl: 5.010
resources:
  bugtracker: https://github.com/JRaspass/JavaBin/issues
  repository: git://github.com/JRaspass/JavaBin.git
version: 0.5
